// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  angular.module('roadpinFrontendApp').controller('AppCtrl', ['$scope', '$location', '$resource', '$rootScope', 'version'].concat(function($scope, $location, $resource, $rootScope, version){
    var getClass, awesomeThings, url, QueryData, the_data, gridOptions;
    $scope.version = version;
    console.log('$location.path():', $location.path());
    $scope.$watch(function(){
      return $location.path();
    }, function(activeNavId, origActiveNavId){
      console.log('$location.path():', $location.path(), 'active-nav-id:', activeNavId, 'orig-active-nav-id', origActiveNavId);
      return $scope.activeNavId = activeNavId, $scope;
    });
    getClass = function(id){
      var result;
      result = $scope.activeNavId === id ? 'active' : '';
      console.log('id:', id, '$scope.active-nav-id:', $scope.activeNavId, 'result:', result);
      return result;
    };
    awesomeThings = ['AngularJS', 'Yeoman', 'Karma', 'brunch', 'livescript'];
    url = 'http://106.187.101.193:5346/get_json_today';
    QueryData = $resource(url);
    the_data = QueryData.query({}, function(){
      return console.log('the_data.length:', the_data.length, 'the_data:', the_data);
    });
    'the_data = [\n  * county_id: "63"\n    county_name: "臺北市"\n    end_timestamp: 1419955200, \n    extension: \n      CASE_LOCATIONpro: "基隆路四段"\n      CASE_STATUSpro: "2"\n      CTR_ONAMEpro: ""\n      WORK_DATEpro: "103/01/01~103/12/31"\n      CASE_TYPEpro: "6" \n      CASE_RANGEpro: "基隆路三段~羅斯福路"\n      CTR_WNAMEpro: "協新營造股份有限公司"\n      REG_NAMEpro: "大安區"\n      dtResultpro: [\n        * P2NAME: null\n          GEO_TYPE: "Polygon"\n          POINTS: [ \n            * P2: 25.015675259737762\n              P1: 121.54238687689245\n            * P2: 25.015364673621825\n              P1: 121.5427080981231\n            * P2: 25.010943705473352\n              P1: 121.53744258838049\n            * P2: 25.01126944425874\n              P1: 121.53720631914334\n            * P2: 25.015151059635382\n              P1: 121.5418922068798\n            * P2: 25.015675259737762\n              P1: 121.54238687689245\n          ]\n          P1NAME: null\n          KEY: null\n      ]\n    geo: [  \n      * type: "LineString", \n        coordinates: [  \n          [ 121.54238687689245 25.015675259737762 ]\n          [ 121.5427080981231 25.015364673621825 ]\n          [ 121.53744258838049 25.010943705473352 ]\n          [ 121.53720631914334 25.01126944425874 ]\n          [ 121.5418922068798 25.015151059635382 ] \n          [ 121.54238687689245 25.015675259737762 ]\n        ]\n    ]\n    start_timestamp: 1388505600\n    the_category: "taipei_city_road_case"\n    the_id: "taipei_city_road_case_5340"\n    the_idx: 5340\n    start_date: "2014-01-01"\n    end_date: "2014-12-31"\n]';
    gridOptions = {
      data: 'the_data',
      enablePaging: true,
      columnDefs: [
        {
          field: 'county_name',
          displayName: '縣市'
        }, {
          field: 'town_name',
          displayName: '鄉鎮市區'
        }, {
          field: 'location',
          displayName: '施工位置'
        }, {
          field: 'range',
          displayName: '施工範圍'
        }, {
          field: 'beginDate',
          displayName: '開始時間'
        }, {
          field: 'endDate',
          displayName: '結束時間'
        }, {
          field: 'work_institute',
          displayName: '施工單位'
        }, {
          field: 'work_institute2',
          displayName: '(施工相關機構)'
        }
      ]
    };
    return $scope.getClass = getClass, $scope.awesomeThings = awesomeThings, $scope.the_data = the_data, $scope.gridOptions = gridOptions, $scope;
  }));
}).call(this);
