// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var cached_data, is_first;
  cached_data = {
    data: {}
  };
  is_first = true;
  angular.module('roadpinFrontendApp').service('jsonToday', function(){
    var url, QueryData, the_data;
    if (!is_first) {
      return cached_data.data;
    }
    url = 'http://106.187.101.193:5346/get_json_today';
    QueryData = $resource(url);
    the_data = QueryData.query({}, function(){
      console.log('the_data.length:', the_data.length, 'the_data:', the_data);
      import$(cached_data.data, the_data);
      return console.log('cached_data.data.length:', cached_data.data.length, 'cached_data.data:', cached_data.data);
    });
    return cached_data.data;
  });
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
